(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "JINT_CONTROL"
   "<JINT_CONTROL-REQUEST>"
   "JINT_CONTROL-REQUEST"
   "<JINT_CONTROL-RESPONSE>"
   "JINT_CONTROL-RESPONSE"
   "OINT_CONTROL"
   "<OINT_CONTROL-REQUEST>"
   "OINT_CONTROL-REQUEST"
   "<OINT_CONTROL-RESPONSE>"
   "OINT_CONTROL-RESPONSE"
  ))

