// Generated by gencpp from file beginner_tutorials/oint_point.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_OINT_POINT_H
#define BEGINNER_TUTORIALS_MESSAGE_OINT_POINT_H

#include <ros/service_traits.h>


#include <beginner_tutorials/oint_pointRequest.h>
#include <beginner_tutorials/oint_pointResponse.h>


namespace beginner_tutorials
{

struct oint_point
{

typedef oint_pointRequest Request;
typedef oint_pointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct oint_point
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::oint_point > {
  static const char* value()
  {
    return "dddedc15b36c5ba529f4bc4fa44289e0";
  }

  static const char* value(const ::beginner_tutorials::oint_point&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::oint_point > {
  static const char* value()
  {
    return "beginner_tutorials/oint_point";
  }

  static const char* value(const ::beginner_tutorials::oint_point&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::oint_pointRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::oint_point > 
template<>
struct MD5Sum< ::beginner_tutorials::oint_pointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::oint_point >::value();
  }
  static const char* value(const ::beginner_tutorials::oint_pointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::oint_pointRequest> should match 
// service_traits::DataType< ::beginner_tutorials::oint_point > 
template<>
struct DataType< ::beginner_tutorials::oint_pointRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::oint_point >::value();
  }
  static const char* value(const ::beginner_tutorials::oint_pointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::oint_pointResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::oint_point > 
template<>
struct MD5Sum< ::beginner_tutorials::oint_pointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::oint_point >::value();
  }
  static const char* value(const ::beginner_tutorials::oint_pointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::oint_pointResponse> should match 
// service_traits::DataType< ::beginner_tutorials::oint_point > 
template<>
struct DataType< ::beginner_tutorials::oint_pointResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::oint_point >::value();
  }
  static const char* value(const ::beginner_tutorials::oint_pointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_OINT_POINT_H
