// Generated by gencpp from file beginner_tutorials/Oint_Control.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_OINT_CONTROL_H
#define BEGINNER_TUTORIALS_MESSAGE_OINT_CONTROL_H

#include <ros/service_traits.h>


#include <beginner_tutorials/Oint_ControlRequest.h>
#include <beginner_tutorials/Oint_ControlResponse.h>


namespace beginner_tutorials
{

struct Oint_Control
{

typedef Oint_ControlRequest Request;
typedef Oint_ControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Oint_Control
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::Oint_Control > {
  static const char* value()
  {
    return "1875e42e845027bd6fcfaa530591c368";
  }

  static const char* value(const ::beginner_tutorials::Oint_Control&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::Oint_Control > {
  static const char* value()
  {
    return "beginner_tutorials/Oint_Control";
  }

  static const char* value(const ::beginner_tutorials::Oint_Control&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::Oint_ControlRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Oint_Control > 
template<>
struct MD5Sum< ::beginner_tutorials::Oint_ControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Oint_Control >::value();
  }
  static const char* value(const ::beginner_tutorials::Oint_ControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::Oint_ControlRequest> should match 
// service_traits::DataType< ::beginner_tutorials::Oint_Control > 
template<>
struct DataType< ::beginner_tutorials::Oint_ControlRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Oint_Control >::value();
  }
  static const char* value(const ::beginner_tutorials::Oint_ControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::Oint_ControlResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Oint_Control > 
template<>
struct MD5Sum< ::beginner_tutorials::Oint_ControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Oint_Control >::value();
  }
  static const char* value(const ::beginner_tutorials::Oint_ControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::Oint_ControlResponse> should match 
// service_traits::DataType< ::beginner_tutorials::Oint_Control > 
template<>
struct DataType< ::beginner_tutorials::Oint_ControlResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Oint_Control >::value();
  }
  static const char* value(const ::beginner_tutorials::Oint_ControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_OINT_CONTROL_H
