// Generated by gencpp from file beginner_tutorials/Jint_Control.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_JINT_CONTROL_H
#define BEGINNER_TUTORIALS_MESSAGE_JINT_CONTROL_H

#include <ros/service_traits.h>


#include <beginner_tutorials/Jint_ControlRequest.h>
#include <beginner_tutorials/Jint_ControlResponse.h>


namespace beginner_tutorials
{

struct Jint_Control
{

typedef Jint_ControlRequest Request;
typedef Jint_ControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Jint_Control
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::Jint_Control > {
  static const char* value()
  {
    return "27dce5e8a7342082f1bb452fe4d0a953";
  }

  static const char* value(const ::beginner_tutorials::Jint_Control&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::Jint_Control > {
  static const char* value()
  {
    return "beginner_tutorials/Jint_Control";
  }

  static const char* value(const ::beginner_tutorials::Jint_Control&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::Jint_ControlRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Jint_Control > 
template<>
struct MD5Sum< ::beginner_tutorials::Jint_ControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Jint_Control >::value();
  }
  static const char* value(const ::beginner_tutorials::Jint_ControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::Jint_ControlRequest> should match 
// service_traits::DataType< ::beginner_tutorials::Jint_Control > 
template<>
struct DataType< ::beginner_tutorials::Jint_ControlRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Jint_Control >::value();
  }
  static const char* value(const ::beginner_tutorials::Jint_ControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::Jint_ControlResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Jint_Control > 
template<>
struct MD5Sum< ::beginner_tutorials::Jint_ControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Jint_Control >::value();
  }
  static const char* value(const ::beginner_tutorials::Jint_ControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::Jint_ControlResponse> should match 
// service_traits::DataType< ::beginner_tutorials::Jint_Control > 
template<>
struct DataType< ::beginner_tutorials::Jint_ControlResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Jint_Control >::value();
  }
  static const char* value(const ::beginner_tutorials::Jint_ControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_JINT_CONTROL_H
