// Generated by gencpp from file beginner_tutorials/Jint_ControlRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_JINT_CONTROLREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_JINT_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Jint_ControlRequest_
{
  typedef Jint_ControlRequest_<ContainerAllocator> Type;

  Jint_ControlRequest_()
    : typ(0)
    , t1(0.0)
    , t2(0.0)
    , t3(0.0)
    , time(0.0)  {
    }
  Jint_ControlRequest_(const ContainerAllocator& _alloc)
    : typ(0)
    , t1(0.0)
    , t2(0.0)
    , t3(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _typ_type;
  _typ_type typ;

   typedef float _t1_type;
  _t1_type t1;

   typedef float _t2_type;
  _t2_type t2;

   typedef float _t3_type;
  _t3_type t3;

   typedef float _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Jint_ControlRequest_

typedef ::beginner_tutorials::Jint_ControlRequest_<std::allocator<void> > Jint_ControlRequest;

typedef boost::shared_ptr< ::beginner_tutorials::Jint_ControlRequest > Jint_ControlRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::Jint_ControlRequest const> Jint_ControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/seba/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4bea38b68db5f09da552c90010c046f";
  }

  static const char* value(const ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4bea38b68db5f09ULL;
  static const uint64_t static_value2 = 0xda552c90010c046fULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Jint_ControlRequest";
  }

  static const char* value(const ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 typ\n\
float32 t1\n\
float32 t2\n\
float32 t3\n\
float32 time\n\
";
  }

  static const char* value(const ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.typ);
      stream.next(m.t1);
      stream.next(m.t2);
      stream.next(m.t3);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Jint_ControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Jint_ControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "typ: ";
    Printer<int8_t>::stream(s, indent + "  ", v.typ);
    s << indent << "t1: ";
    Printer<float>::stream(s, indent + "  ", v.t1);
    s << indent << "t2: ";
    Printer<float>::stream(s, indent + "  ", v.t2);
    s << indent << "t3: ";
    Printer<float>::stream(s, indent + "  ", v.t3);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_JINT_CONTROLREQUEST_H
